config/routes.rb
MapsApp::Application.routes.draw do
  root to: "main#index"
  root to: "folders#index"

  resources :folders
  resources :links

end

app/models/folder.rb
class Folder < ActiveRecord::Base
  attr_accessible :name
  has_many :links
end

app/models/link.rb
class Link < ActiveRecord::Base
  attr_accessible :folder_id, :name
  belongs_to :folder
  # mount_uploader :image, ImageUploaderend
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/folders_controller.rb
class FoldersController < ApplicationController
  def index
    @folders = Folder.all
  end

  def show
    @folder = Folder.find(params[:id])
  end

  def new
    @folder = Folder.new
  end

  def create
    @folder = Folder.new(params[:folder])
    if @folder.save
      flash[:notice] = "Successfully created folder."
      redirect_to @folder
    else
      render :action => 'new'
    end
  end

  def edit
    @folder = Folder.find(params[:id])
  end

  def update
    @folder = Folder.find(params[:id])
    if @folder.update_attributes(params[:folder])
      flash[:notice] = "Successfully updated folder."
      redirect_to folder_url
    else
      render :action => 'edit'
    end
  end

  def destroy
    @folder = Folder.find(params[:id])
    @folder.destroy
    flash[:notice] = "Successfully destroyed Folder."
    redirect_to folders_url
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController

  def new
    @link = Link.new(:folder_id => params[:folder_id])
    puts "NEW link"
  end

  def create
    @link = Link.new(params[:link])
    if @link.save
      flash[:notice] = "Successfully created file."
      redirect_to @link.folder
    else
      render :action => 'new'
    end
  end

  def edit
    @link = Link.find(params[:id])
  end

  def update
    @link = Link.find(params[:id])
    if @link.update_attributes(params[:link])
      flash[:notice] = "Successfully updated file."
      redirect_to @link.folder
    else
      render :action => 'edit'
    end
  end

  def destroy
    @link = Link.find(params[:id])
    @link.destroy
    flash[:notice] = "Successfully destroyed file."
    redirect_to @link.folder
  end

end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= "Invalid Fields"
    options[:message] ||= "Correct the following errors and try again."
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/folders_helper.rb
module FoldersHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/folders/_form.html.haml
= form_for @folder do |f|
  = f.error_messages
  %p
    = f.label :name
    %br/
    = f.text_field :name
  %p= f.submit

app/views/folders/edit.html.haml
.title New Gallery
= render 'form'
%p
  = link_to "Show", @folder
  |
  \#{link_to "View All", folders_path}

app/views/folders/index.html.haml
.title Galleries
- @folders.each do |folder|
  .folder
    %h2= link_to folder.name, folder
    Links: #{folder.links.size}
%p= link_to "New Gallery", new_folder_path

app/views/folders/new.html.haml
.title New Gallery
= render 'form'
%p= link_to "Back to List", folders_path

app/views/folders/show.html.haml
.title 
  =@folder.name
#links
  - @folder.links.each do |link|
    .link
      .name= link.name
      .actions
        = link_to "edit", edit_link_path(link)
        |
        \#{link_to "remove", link, :confirm => 'Are you sure?', :method => :delete}
  .clear
%p
  = link_to "Add a file", new_link_path(:folder_id => @folder)
  |
  \#{link_to "Remove Gallery", @folder, :confirm => 'Are you sure?', :method => :delete} |
  \#{link_to "View Galleries", folders_path}

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MapsApp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/links/_form.html.haml
= form_for @link, :html => {:multipart => true} do |f|
  = f.error_messages
  = f.hidden_field :folder_id
  %p
    = f.label :name
    %br/
    = f.text_field :name
  %p= f.submit

app/views/links/edit.html.haml
.title Edit File
= render 'form'
%p= link_to "Back to Folder", @link.folder

app/views/links/new.html.haml
.title New Painting
= render 'form'
%p= link_to "Back to Gallery", @link.folder 

app/views/main/index.html.haml
#container 
  Loading..